### ISSUE TITLE
worker initialization failed: there is no package called 'RRgeo'

### ISSUE THREAD

**Issue by accaragao** [pasraia/ENphylo-test-files#1]
Hi,
In "ENphylo model predictions and mapping.R", when i run the line:
```
enfa_test<-ENphylo_modeling(input_data=DATA_FULL[k],
                            input_mask=MASK_FULL,
                            tree=tree,
                            obs_col="OBS",
                            time_col="TIME_factor",
                            min_occ_enfa=npoints-1,
                            eval_metric_for_imputation="AUC",
                            output_options = "best",
                            eval_threshold=0.5)
```
I got the error message:
`Error in e$fun(obj, substitute(ex), parent.frame(), e$data) :  worker initialization failed: there is no package called 'RRgeo'.`
But I can't find this package in any repository.

Thanks in advance!
Ana

**Comment by pasraia** [comment]
Hi Ana,
this issue was fixed a few days ago. You should reinstall the package (which is now v 0.5.6) and find this problem solved. Please notice, the latest versions of RRdtn work with terra/sf insted of raster/sp, and some of the arguments have been grouped together. In your particular case, the object MASK_FULL should be assigned by terra::rast(...) and the arguments eval_metric_for_imputation="AUC", output_options = "best", eval_threshold=0.5 must be supplied to the function as eval.args=list(eval_metric_for_imputation="AUC", output_options = "best", eval_threshold=0.5). Everything new is documented in the help pages of RRdtn 0.5.6.
Hope this helps
Cheers
Pas

**Comment by accaragao** [comment]
Hi Pas,
Thank you for your rapid reply!
It works now!
